Repository QuiltMC/quiltmc.org, pull requests merged in 2024-04, with the labels that each got.

#194 Beneath the Wetlands Incompatibility
  public/incompatible-mods.json
Labels: incompatible mod

#195 add quilt config to changelog aggregator
  scripts/preprocess.mjs
Labels: enhancement

#196 Cook the incompatible mod list
  package-lock.json
  package.json
  public/_redirects
  public/api/v1/incompatible-mods.json
  public/assets/img/unknown.png
  public/incompatible-mods.json
  src/components/atoms/IncompatibleModCard.astro
  src/layouts/KnownIncompatibilities.astro
  src/pages/en/usage/known-incompatibilities.mdx
Labels: enhancement

#199 fix typo in feb update and add march update
  public/assets/img/writing/blog/2024-04-08-quilt-update/mapping-comparison.png
  src/pages/en/blog/2024-03-09-quilt-update.md
  src/pages/en/blog/2024-04-08-quilt-update.md
Labels: blog post

#198 API home page
  .gitignore
  package-lock.json
  package.json
  public/_headers
  public/api/openapi.yaml
  src/components/setpieces/HtmlHead.astro
  src/components/setpieces/NavBar.astro
  src/locales/en/common.flt
  src/pages/api.astro
  src/styles/swagger-dark.css
Labels: enhancement

#200 Add search
  astro.config.ts
  package-lock.json
  package.json
  src/components/parts/nav/Search.astro
  src/components/setpieces/NavBar.astro
  src/integration/search-index.ts
  src/layouts/Home.astro
  src/layouts/PatchNotes.astro
  src/layouts/StaffDocument.astro
  src/script.ts
  tsconfig.json
Labels: enhancement

#203 Loader changelogs
  package-lock.json
  package.json
  scripts/preprocess.mjs
  scripts/util.mjs
  src/pages/en/changelog/[project]/[version].astro
  src/pages/en/changelog/index.astro
Labels: enhancement

#202 Import utilities: Last version and mod generator
  .gitignore
  README.md
  functions/api/internal/download-template-mod.js
  functions/api/v1/latest-version-components.js
  package-lock.json
  package.json
  public/api/openapi.yaml
  public/assets/css/prism-material-dark.css
  public/assets/css/prism-material-light.css
  public/assets/license-templates/MIT
  public/assets/license-templates/MPL-2.0
  public/assets/license-templates/PolyForm-Shield-1.0.0
  public/assets/license-templates/Unlicense
  src/components/setpieces/HtmlHead.astro
  src/layouts/Generator.astro
  src/layouts/HeroBase.astro
  src/layouts/LatestVersions.astro
  src/locales/en/common.flt
  src/pages/api.astro
  src/pages/en/usage/generator.mdx
  src/pages/en/usage/latest-versions.mdx
Labels: enhancement

#205 attempt to fix version sorting and misc cleanup (fixes #204)
  functions/api/v1/latest-version-components.js
  src/components/setpieces/NavBar.astro
  src/layouts/LatestVersions.astro
  src/locales/en/common.flt
  src/locales/zh/common.flt
  src/pages/en/usage/index.mdx
Labels: bug, enhancement

#163 Privacy policy updates
  src/pages/en/legal/cozy-privacy-policy.mdx
  src/pages/en/legal/index.mdx
  src/pages/en/legal/metricity-privacy-policy.mdx
  src/pages/en/legal/modmail-privacy-policy.mdx
Labels: documentation
