Repository QuiltMC/quiltmc.org, pull requests merged in 2024-03, with the labels that each got.

#187 feb quilt update
  public/assets/img/writing/blog/2024-03-09-quilt-update/mapping-comparison.png
  src/pages/en/blog/2024-03-09-quilt-update.md
Labels: blog post

#189 add creative core incompatibility
  public/incompatible-mods.json
Labels: incompatible mod

#183 fix wiki link going to a redirect page
  src/data/Site.ts
Labels: bug

#184 Project changelogs
  public/_redirects
  scripts/paths.mjs
  scripts/preprocess.mjs
  src/components/setpieces/NavBar.astro
  src/components/setpieces/Sidebar.astro
  src/locales/en/common.flt
  src/pages/en/changelog/[project]/[version].astro
  src/pages/en/changelog/index.astro
  src/pages/qsl.astro
  src/util/Util.ts
Labels: enhancement

#185 update gdlauncher install page and reorganise install page
  src/components/atoms/InstallerButton.astro
  src/components/parts/install/Awaiting.astro
  src/components/parts/install/Launchers.astro
  src/layouts/Install.astro
  src/layouts/InstallPage.astro
  src/pages/en/install/client.mdx
  src/pages/en/install/gdlauncher.mdx
  src/pages/en/install/index.mdx
Labels: enhancement

#192 bump used actions versions
  .github/workflows/commit-preview.yaml
  .github/workflows/manual-publish.yaml
  .github/workflows/pr-preview-footer.yaml
  .github/workflows/pr-preview.yaml
  .github/workflows/publish-pr-preview.yaml
  .nvmrc
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: enhancement
