Repository QuiltMC/quiltmc.org, pull requests merged in 2024-02, with the labels that each got.

#178 Update url used for querying patchnotes
  src/layouts/PatchNotes.astro
Labels: bug

#180 jan quilt update
  public/assets/img/writing/blog/2024-02-12-quilt-update/enigma_bytecode.png
  public/assets/img/writing/blog/2024-02-12-quilt-update/mapping_stats.png
  public/assets/img/writing/blog/2024-02-12-quilt-update/oro_armor.png
  src/pages/en/blog/2024-02-12-quilt-update.md
Labels: blog post

#158 note that telemetry has been removed on blog posts
  src/pages/en/blog/2023-06-26-mau-beacon.md
  src/pages/en/blog/2023-07-12-quilt-telemetry-explained.md
Labels: documentation

#182 fix next and last buttons on blog being inverted
  package-lock.json
  src/components/setpieces/Paginator.astro
Labels: bug
