Repository QuiltMC/quiltmc.org, pull requests merged in 2024-05, with the labels that each got.

#217 Fix scripts running when they should not
  package-lock.json
  package.json
  src/components/parts/install/InstallerVersion.astro
  src/pages/api.astro
Labels: bug

#220 Restore/improve patchnote behaviour
  src/layouts/PatchNotes.astro
Labels: bug, enhancement

#218 Use builtin date instead of querying meta
  src/layouts/PatchNotes.astro
Labels: enhancement
